name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Cover 
            uses: orgoro/coverage@v3.2
            with:
                coverageFile: coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}
                thresholdNew: 0.5
                thresholdModified: 0.0
                thresholdAll: 0.25
